spin_manifest_version = "1"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "Get latest GFS run from AWS Open Data."
name = "spin-python-latest-gfs"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "gfs_latest"
source = "gfs_latest.wasm"
allowed_http_hosts = ["https://noaa-gfs-bdp-pds.s3.amazonaws.com"]
[component.trigger]
route = "/gfs/latest/..."
[component.build]
command = "spin py2wasm gfs_latest -o gfs_latest.wasm"
